### ISSUE TITLE
Grass block breaking with New claiming system

### ISSUE THREAD

**Issue by Mikecraft28** [SleepingTea98/Mythic-Modpack#1]
I stil am able to break other people their grass Dort gravel and sand in the werewolf form if the old claiming system wont get deleted and u just claim 2 times once with old once with the golden shovel

**Comment by SleepingTea98** [comment]
Thanks for letting us know, we'll look into fixing the issue.

We can't leave the old claim system and the new system in place as this would lead to players claiming over bases that have only claimed with the one system.

**Comment by SleepingTea98** [comment]
Should now be fixed
