### ISSUE TITLE
My player appears to be slightly broken. 

### ISSUE THREAD

**Issue by maffasaur** [SleepingTea98/Mythic-Modpack#10]
Foremost: I never had these issues before yesterday so I have no clue what happened.

I can no longer get research notes from thaumcraft. When I click on undiscovered research, it doesn't ding or give me a new note. The message comes up saying it's in my inventory but it isn't. 

Adding onto that, probably unrelated but also an issue, my tamed animals won't stand when I ask them to. I've been trying to bind a familar but it wont work because it seems to think the cat doesn't exist.

**Comment by therealphyzz** [comment]
I'm having the exact same issue, IGN TheRealPhyzz
