### ISSUE TITLE
SkinPort, Twitch

### ISSUE THREAD

**Issue by Math321** [SleepingTea98/Mythic-Modpack#15]
The Twitch version of the pack is slightly messed up. The server has SkinPort version v9b, but the Twitch pack has v9d. Either the server needs updated or the client needs UNupdated.

**Comment by Math321** [comment]
Note - I don't know if this problem exists on the Technic version of the pack (since I don't use it), but it'd be worth checking.

**Comment by SleepingTea98** [comment]
Twitch versions are now being updated. Issue fixed
