### ISSUE TITLE
Blood magic Life essence permanently stuck

### ISSUE THREAD

**Issue by Likecheckers** [SleepingTea98/Mythic-Modpack#17]
My in-game username is Likecheckers. my life essence is permanently stuck at 287,467 no matter what i do i can't get it to go down or up. my blood orbs don't fill even though their capacity is supposed to be 15million and i can fire my energy bazooka constantly which is supposed to cost 20k per shot for nothing. this may sound good for me but this locks me out of many of the high end rituals to advance since a few of them cost 15m

**Comment by SleepingTea98** [comment]
This is an issue with the mod, please report it to the mod makers. Thanks!
