### ISSUE TITLE
Beds have a fixed camera angle...

### ISSUE THREAD

**Issue by BrotherLeon** [SleepingTea98/Mythic-Modpack#19]
When I used both a Decocraft bed with canvas and a carpenter's bed, the angle of my view when in bed was fixed looking directly north. I tested this with the carpenter's bed specifically, but observed behaviour from the Decocraft bed consistent with the testing from the Carpenter's Bed.

**Comment by SleepingTea98** [comment]
This is an error with the mod, please report it to the mod makers. Thanks!
