### ISSUE TITLE
Claim bug on mythic

### ISSUE THREAD

**Issue by Death4200** [SleepingTea98/Mythic-Modpack#21]
When I try to resize my claim from the corners and then put the corner on a new place, it says that it can't be resized because the claim would overlap other nearby players claim. However, after that, the red claim line, which shows other players claim, is shown on my claim lines.

**Comment by jarinawer** [comment]
hello, I found an object in a chest and took it but the minecraft closed, and every time I try to open it and enter the server it closes, is there any admin that can delete my inventory?

**Comment by jarinawer** [comment]
the object is item.infitool.name of tinkers construct

**Comment by SleepingTea98** [comment]
The issue has been added to our bug tracker and we're currently looking into it.
