### ISSUE TITLE
Ars magica level and progress reset

### ISSUE THREAD

**Issue by Sonsofsiths** [SleepingTea98/Mythic-Modpack#23]
I added heart canisters to increase my health and now all of my ars magica progress is gone I was level 13 but had bought orbs recent making it to where I had over 30 blue skill points around 8 green ones and 6 red one please help thank you

**Comment by SleepingTea98** [comment]
The issue has been added to our bug tracker and we're currently looking into it. If you would like a refund of items, please open a ticket on our forums.
