### ISSUE TITLE
Soul fragment taking 4 hearts instead of 1.

### ISSUE THREAD

**Issue by SP00NERMAN** [SleepingTea98/Mythic-Modpack#3]
i was attempting to make the reinforced watering can, and after i made it the soul fragment took 4 of my hearts instead of one, idk if you have any say over the mythic server but if so thats what im on and would like to know if there is a way to get my hearts back. IGN is: SP00NERMAN

**Comment by LatridellActiveX** [comment]
This is a known issue and related to the mod itself. It results when you shift click the item as opposed to moving it with the cursor.

**Comment by SleepingTea98** [comment]
Please report this to the mod maker.
