### ISSUE TITLE
GriefPrevention Issue

### ISSUE THREAD

**Issue by LatridellActiveX** [SleepingTea98/Mythic-Modpack#4]
When talking about a specific area of land claimed with a golden shovel:
When using the command /abandonallclaims or alternatively /abandonclaim the area is unclaimed and able to be modified by the public, however, any attempts to claim over the recently abandoned claim results in a notification that the area overlaps a claim. 

A stick is not able to detect any land claimed in the recently abandoned area. 

This issue affects plots in the player market and I am able to replicate this bug apon request. Direct any questions to me here or on the discord @latridell#5583

**Comment by SleepingTea98** [comment]
We know of this issue from other servers and are looking into it.

Thanks!
