### ISSUE TITLE
Golemancer's bell bug

### ISSUE THREAD

**Issue by ReboundQ3** [SleepingTea98/Mythic-Modpack#5]
When i try to craft a golemmancer's bell i instantly crash, but when you look at the name before you craft the item it sais "Golemmancer's bell -1" 
Please fix this its annoying as hell

**Comment by ReboundQ3** [comment]
![image](https://user-images.githubusercontent.com/22770594/55683342-e406b500-593e-11e9-8d86-d319940287b4.png)

**Comment by SleepingTea98** [comment]
Sorry, this isn't an issue we can fix. Please report this issue to the mod maker
