### ISSUE TITLE
Claim blocks

### ISSUE THREAD

**Issue by GalaxyTraveler5** [SleepingTea98/Mythic-Modpack#8]
My player, Galaxytraveler5 has a negative amount of claim blocks (-12k) any time it goes into the positive I try to expand my claim and it immediately goes back into the negative, I think when it claims it accounts for every block in the claim rather than the ones I expanded to

![blocks](https://user-images.githubusercontent.com/49582471/56076395-69e29000-5d85-11e9-9f05-e505be43a4e9.png)

**Comment by SleepingTea98** [comment]
I've added some more claim blocks to your account. Should be fixed now. 

Sorry about that!
