### ISSUE TITLE
Failed to download 

### ISSUE THREAD

**Issue by Jetzap25** [SleepingTea98/Mythic-Modpack#9]
Everytime I attemp to download this modpack on the technic launcher I get the following error code
![Capture](https://user-images.githubusercontent.com/49583707/56077198-9dbcc480-5e1c-11e9-8512-745e53cda9bc.PNG)
This hasn't happend with any other modpack
HELP

**Comment by SleepingTea98** [comment]
Sorry, this is an issue on your end. We've had no other reports of download issues.

If you need help with this please join our Discord.
